export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SET_MESSAGE = "SET_MESSAGE";
export const FIND_PRODUCT_FAIL = "FIND_PRODUCT_FAIL";
export const FIND_PRODUCT_SUCCESS = "FIND_PRODUCT_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const SET_STATUS = "SET_STATUS";
export const LOGOUT = "LOGOUT";
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
export const UPDATE_CART_FAIL = "UPDATE_CART_FAIL";
export const FIND_CART_FAIL = "UPDATE_CART_FAIL";
export const FIND_CART_SUCCESS = "UPDATE_CART_SUCCESS";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_FAIL = "ORDER_FAIL";
export const DELETE_ITEM_CART_SUCCESS = "DELETE_ITEM_CART_SUCCESS";
export const DELETE_ITEM_CART_FAIL = "DELETE_ITEM_CART_FAIL";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";








